#!/usr/bin/env python3
"""
Script para mostrar la configuración actual y opciones de detección de rostros
"""

def show_help():
    print("🔧 CONFIGURACIÓN DE DETECCIÓN DE ROSTROS")
    print("=" * 60)
    print()
    print("📋 PARÁMETROS DISPONIBLES:")
    print("  -s, --source SOURCE_PATH          Imagen fuente")
    print("  -t, --target TARGET_PATH          Video objetivo")
    print("  -o, --output OUTPUT_PATH          Archivo de salida")
    print("  --frame-processor                 Procesadores de frames")
    print("  --keep-fps                        Mantener FPS original")
    print("  --keep-frames                     Mantener frames temporales")
    print("  --skip-audio                      Omitir audio")
    print("  --many-faces                      Procesar todos los rostros")
    print("  --reference-face-position         Posición del rostro de referencia")
    print("  --reference-frame-number          Número del frame de referencia")
    print("  --similar-face-distance           Distancia para reconocimiento")
    print("  --temp-frame-format               Formato de frames temporales")
    print("  --temp-frame-quality              Calidad de frames temporales")
    print("  --output-video-encoder            Codificador de video")
    print("  --output-video-quality            Calidad de video de salida")
    print("  --max-memory                      Memoria máxima en GB")
    print("  --execution-provider              Proveedor de ejecución")
    print("  --execution-threads               Número de hilos")
    print()
    print("🎯 CONFIGURACIÓN ACTUAL EN batch_processor.py:")
    print("  • Videos se procesan en orden alfabético")
    print("  • Detección automática de tipos de video")
    print("  • Procesamiento de múltiples rostros")
    print("  • Calidad máxima de frames temporales")
    print("  • 🤖 ANÁLISIS AUTOMÁTICO ACTIVADO")
    print()
    print("🤖 ANÁLISIS AUTOMÁTICO:")
    print("  • Detecta automáticamente características del video")
    print("  • Configura parámetros óptimos sin intervención manual")
    print("  • Analiza resolución, calidad, rostros, etc.")
    print("  • Guarda resultados en cache para reutilizar")
    print()
    print("📁 TIPOS DE VIDEO DETECTADOS AUTOMÁTICAMENTE:")
    print("  • 'group' o 'multiple': Videos con múltiples personas")
    print("  • 'closeup' o 'portrait': Videos con rostros cercanos")
    print("  • 'low_quality': Videos de baja calidad")
    print("  • 🔍 ANÁLISIS AUTOMÁTICO: Detecta todo automáticamente")
    print()
    print("💡 CONSEJOS PARA MEJORAR LA DETECCIÓN:")
    print("  • Si no detecta bien los rostros:")
    print("    - Reduce 'similar_face_distance' a 0.75")
    print("    - Aumenta 'temp_frame_quality' a 100")
    print("    - Usa '--many-faces' para múltiples rostros")
    print("    - 🚀 O usa el análisis automático que lo hace todo solo")
    print()
    print("  • Para rostros pequeños o lejanos:")
    print("    - Aumenta 'temp_frame_quality'")
    print("    - Reduce 'similar_face_distance'")
    print("    - Usa '--reference-face-position 0'")
    print("    - 🤖 El análisis automático detecta esto y ajusta parámetros")
    print()
    print("  • Para videos con múltiples personas:")
    print("    - Usa '--many-faces'")
    print("    - Ajusta 'similar_face_distance' a 0.80")
    print("    - 🤖 El análisis automático detecta múltiples rostros")
    print()
    print("🔧 CÓMO PERSONALIZAR:")
    print("  1. 🚀 ANÁLISIS AUTOMÁTICO (RECOMENDADO):")
    print("     python setup_auto_analysis.py")
    print("     python face_config.py analyze")
    print("     python batch_processor.py")
    print()
    print("  2. 📝 CONFIGURACIÓN MANUAL:")
    print("     Edita 'face_config.py' para cambiar parámetros")
    print("     Nombra tus videos con palabras clave (group, closeup, etc.)")
    print("     Ejecuta: python batch_processor.py")
    print()
    print("📊 USO:")
    print("  🚀 CONFIGURACIÓN AUTOMÁTICA:")
    print("    python setup_auto_analysis.py    - Instalar y configurar")
    print("    python face_config.py analyze    - Analizar todos los videos")
    print("    python batch_processor.py        - Procesar automáticamente")
    print()
    print("  📋 INFORMACIÓN Y AYUDA:")
    print("    python show_config.py            - Esta ayuda")
    print("    python face_config.py            - Configuración actual")
    print("    python video_analyzer.py <video> - Analizar video específico")
    print()
    print("✨ VENTAJAS DEL ANÁLISIS AUTOMÁTICO:")
    print("  • No necesitas saber el formato del video")
    print("  • Detecta automáticamente la calidad y características")
    print("  • Configura parámetros óptimos para cada video")
    print("  • Aprende de cada análisis para mejorar futuros procesamientos")
    print("  • Guarda tiempo y mejora la calidad de los resultados")

if __name__ == "__main__":
    show_help() 