#!/usr/bin/env python3
"""
Script para mostrar la configuración actual y opciones de detección de rostros
"""

def show_help():
    print("🔧 CONFIGURACIÓN DE DETECCIÓN DE ROSTROS")
    print("=" * 60)
    print()
    print("📋 PARÁMETROS DISPONIBLES:")
    print("  -s, --source SOURCE_PATH          Imagen fuente")
    print("  -t, --target TARGET_PATH          Video objetivo")
    print("  -o, --output OUTPUT_PATH          Archivo de salida")
    print("  --frame-processor                 Procesadores de frames")
    print("  --keep-fps                        Mantener FPS original")
    print("  --keep-frames                     Mantener frames temporales")
    print("  --skip-audio                      Omitir audio")
    print("  --many-faces                      Procesar todos los rostros")
    print("  --reference-face-position         Posición del rostro de referencia")
    print("  --reference-frame-number          Número del frame de referencia")
    print("  --similar-face-distance           Distancia para reconocimiento")
    print("  --temp-frame-format               Formato de frames temporales")
    print("  --temp-frame-quality              Calidad de frames temporales")
    print("  --output-video-encoder            Codificador de video")
    print("  --output-video-quality            Calidad de video de salida")
    print("  --max-memory                      Memoria máxima en GB")
    print("  --execution-provider              Proveedor de ejecución")
    print("  --execution-threads               Número de hilos")
    print()
    print("🎯 CONFIGURACIÓN ACTUAL EN batch_processor.py:")
    print("  • Videos se procesan en orden alfabético")
    print("  • Detección automática de tipos de video")
    print("  • Procesamiento de múltiples rostros")
    print("  • Calidad máxima de frames temporales")
    print()
    print("📁 TIPOS DE VIDEO DETECTADOS AUTOMÁTICAMENTE:")
    print("  • 'group' o 'multiple': Videos con múltiples personas")
    print("  • 'closeup' o 'portrait': Videos con rostros cercanos")
    print("  • 'low_quality': Videos de baja calidad")
    print()
    print("💡 CONSEJOS PARA MEJORAR LA DETECCIÓN:")
    print("  • Si no detecta bien los rostros:")
    print("    - Reduce 'similar_face_distance' a 0.75")
    print("    - Aumenta 'temp_frame_quality' a 100")
    print("    - Usa '--many-faces' para múltiples rostros")
    print()
    print("  • Para rostros pequeños o lejanos:")
    print("    - Aumenta 'temp_frame_quality'")
    print("    - Reduce 'similar_face_distance'")
    print("    - Usa '--reference-face-position 0'")
    print()
    print("  • Para videos con múltiples personas:")
    print("    - Usa '--many-faces'")
    print("    - Ajusta 'similar_face_distance' a 0.80")
    print()
    print("🔧 CÓMO PERSONALIZAR:")
    print("  1. Edita 'face_config.py' para cambiar parámetros")
    print("  2. Nombra tus videos con palabras clave (group, closeup, etc.)")
    print("  3. Ejecuta: python batch_processor.py")
    print()
    print("📊 USO:")
    print("  python batch_processor.py")
    print("  python show_config.py")
    print("  python face_config.py")

if __name__ == "__main__":
    show_help() 